#!/bin/sh
#
# Copyright 2007 Google Inc.
# Author: cklin@google.com (Chuan-kai Lin)
#
# lvm
#
case $1 in

	start)
		echo "starting lvm"
		export LVM_SYSTEM_DIR=""
		/sbin/modprobe dm-mod
		/sbin/lvm vgscan
		/sbin/lvm vgchange -ay
		;;

	stop)
		echo "stopping lvm"
		/sbin/lvm vgchange -an
		;;

esac

